Artifisial_fish_swarm/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'Artifisial_fish_swarm'
urlpatterns = [
    path('', include('afs.urls')),
    path('admin/', admin.site.urls, name='amdin'),
]

afs/urls.py
from django.urls import path
from afs import views

app_name = 'afs'
urlpatterns = [
    path('', views.CalculatorView.as_view(), name='calculator'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('login', views.LoginView.as_view(), name='login'),
    path('delete_calculation/<int:calculation_id>', views.DeleteCalculationView.as_view(), name='delete_calculation'),
]

afs/models.py
from django.db import models
from django.contrib.auth.models import User


class Calculation(models.Model):
    functions = (
        ('loss_sphere', 'sphere'),
        ('loss_step', 'step'),
        ('loss_rastrigin', 'rastrigin'),
        ('loss_rosenbrock', 'rosenbrock')
    )
    function = models.CharField(choices=functions, verbose_name='Функция', max_length=15, blank=False)
    param_1 = models.FloatField(verbose_name='Дальность зрения', blank=False)
    param_2 = models.FloatField(verbose_name='Длина шага', blank=False)
    param_3 = models.FloatField(verbose_name='Дельта', blank=False)
    param_4 = models.IntegerField(verbose_name='Количество попыток', blank=False)
    user = models.ManyToManyField(User, verbose_name='Пользователь')
    minima_loss_1 = models.FloatField(verbose_name='Минимум 1', blank=False)
    minima_loss_2 = models.FloatField(verbose_name='Минимум 2', blank=False)

afs/forms.py
from django import forms
from django.contrib.auth import authenticate, login
from afs.models import Calculation


class AuthForm(forms.Form):
    login = forms.CharField(label='Логин')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())

    def __init__(self, *_, **kwargs):
        self.request = kwargs.pop('request')
        super(AuthForm, self).__init__(*_, **kwargs)

    def clean(self, *_, **kwargs):
        username = self.cleaned_data['login']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user:
            login(self.request, user)
        else:
            raise forms.ValidationError(
                {'password': 'Неверные учетные данные'})


class CalculatorForm(forms.ModelForm):
    class Meta:
        model = Calculation
        exclude = ('user', 'minima_loss_1', 'minima_loss_2')
        verbose_name = 'Результат вычислений'
        verbose_name_plural = 'Результаты вычислений'
        widgets = {
            'minima_loss_1': forms.HiddenInput(),
            'minima_loss_2': forms.HiddenInput(),
            'param_1': forms.TextInput(attrs={'placeholder': '0.5'}),
            'param_2': forms.TextInput(attrs={'placeholder': '0.2'}),
            'param_3': forms.TextInput(attrs={'placeholder': '0.5'}),
            'param_4': forms.TextInput(attrs={'placeholder': '5'}),
        }

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, FloatField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign In')


class CalculatorForm(FlaskForm):
    function = SelectField('function', choices=[('1', 'loss sphere'),
                                                ('2', 'loss step'),
                                                ('3', 'loss rastrigin'),
                                                ('4', 'loss rosenbrock')], validators=[DataRequired()])
    param_1 = FloatField('parameter 1', validators=[DataRequired()])
    param_2 = FloatField('parameter 2', validators=[DataRequired()])
    param_3 = FloatField('parameter 3', validators=[DataRequired()])
    param_4 = FloatField('parameter 4', validators=[DataRequired()])
    submit = SubmitField('calculate')

afs/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from afs.models import Calculation
from afs.forms import AuthForm, CalculatorForm

from afs.afs import run


class LoginView(View):
    def get(self, request):
        form = AuthForm(request=request)
        context = {
            'form': form,
            'success_url': request.META.get('HTTP_REFERER', reverse('afs:calculator'))
        }
        return render(request, 'afs/login.html', context)

    def post(self, request):
        success_url = request.POST.get('success_url', reverse('afs:calculator'))

        form = AuthForm(request.POST, request=request)

        if form.is_valid():
            return HttpResponseRedirect(success_url)
        else:
            context = {
                'form': form,
                'success_url': success_url
            }
            return render(request, 'afs/login.html', context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('afs:calculator')))


class CalculatorView(LoginRequiredMixin, View):
    def get(self, request):
        if request.user.is_superuser:
            calculations = Calculation.objects.all().order_by('pk')
        else:
            calculations = Calculation.objects.filter(user=request.user).order_by('pk')
        context = {
            'form': CalculatorForm(),
            'calculations': calculations
        }
        return render(request, 'afs/calculator.html', context)

    def post(self, request):
        user = request.user
        calculations = Calculation.objects.filter(user=user).order_by('pk')

        form = CalculatorForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

            result = run(function=data['function'], param_1=data['param_1'], param_2=data['param_2'],
                         param_3=data['param_3'], param_4=data['param_4'])

            calculation = Calculation.objects.create(function=data['function'],
                                                     param_1=data['param_1'], param_2=data['param_2'],
                                                     param_3=data['param_3'], param_4=data['param_4'],
                                                     minima_loss_1=result['minima_loss_1'],
                                                     minima_loss_2=result['minima_loss_2'])
            calculation.user.set(User.objects.filter(id=request.user.id))

        else:
            context = {
                'form': form,
                'calculations': calculations
            }
            return render(request, 'afs/calculator.html', context)

        return HttpResponseRedirect(reverse('afs:calculator'))


class DeleteCalculationView(LoginRequiredMixin, View):
    def get(self, request, *_, **kwargs):
        Calculation.objects.get(pk=kwargs.get('calculation_id')).delete()
        return HttpResponseRedirect(reverse('afs:calculator'))

afs/templates/afs/base.html
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<div id="wrapper">
    <div id="content">
        <div class="menu">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="{% url 'afs:calculator' %}">Калькулятор</a>
                </div>
                <div>
                    <ul class="nav navbar-nav navbar-right">

                        {% if request.user.is_superuser %}
                            <li><a href="/admin">
                                <span class="glyphicon glyphicon-wrench"></span>
                                admin_panel </a></li>
                        {% endif %}

                        {% if not request.user.is_authenticated %}
                            <li><a href="{% url 'afs:login' %}">
                                <span class="glyphicon glyphicon-log-in"></span>
                                Войти </a></li>

                        {% else %}

                            <li><a href="{% url 'afs:logout' %}">
                                <span class="glyphicon glyphicon-log-out"></span>
                                Выход ({{ request.user }})</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}
    <footer class="card-footer">
            <span class="glyphicon glyphicon-flash">Христенко Полина</span>
        </p>
    </footer>
</div>
</body>

afs/templates/afs/calculator.html
{% extends 'afs/base.html' %}
{% load bootstrap %}
{% block head %}
<title>Калькулятор</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="well">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button class="btn pull-center btn-success"
                    type="submit">
                <span class="glyphicon glyphicon-plus"></span>
                Вычислить
            </button>
        </form>
    </div>
    <div class="row">
    </div>
    {% if calculations %}
    <h4>Результаты вычислений</h4>
    <div class="well">
        <table class="table custab">
            <thead>
            <tr>
                <td class="text-center">Действия</td>
                <td class="text-center">Функция</td>
                <td class="text-center">Дальность зрения</td>
                <td class="text-center">Длина шага</td>
                <td class="text-center">Дельта</td>
                <td class="text-center">Число попыток</td>
                <td class="text-center">Минимум 1</td>
                <td class="text-center">Минимум 2</td>
            </tr>
            </thead>
            {% for calculation in calculations %}
            <tr>
                <td class="text-center">
                    <a href="{% url 'afs:delete_calculation' calculation.id %}"
                       class="btn btn-danger btn-xs"><span
                            class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
                <td class="text-center">{{ calculation.function }}</td>
                <td class="text-center">{{ calculation.param_1 }}</td>
                <td class="text-center">{{ calculation.param_2 }}</td>
                <td class="text-center">{{ calculation.param_3 }}</td>
                <td class="text-center">{{ calculation.param_4 }}</td>
                <td class="text-center">{{ calculation.minima_loss_1 }}</td>
                <td class="text-center">{{ calculation.minima_loss_2 }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endif %}
</div>
{% endblock %}

afs/templates/afs/login.html
{% extends 'afs/base.html' %}
{% load bootstrap %}
{% block head %}
<title>Вход</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        <input type="hidden" value="{{ success_url }}" name="success_url"/>
                        <button class="btn btn-primary pull-center" type="submit">Вход</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<head>
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
{% block content %}{% endblock %}
</body>

templates/calculator.html
{% extends 'base.html' %}
{% block head %}{% endblock %}
{% block content %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div class="container">
    <div class="row">
        <h2>Calculator</h2>
    </div>

    <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
            <form method="post">
                <div class="form-group">
                    {{ form.function.label(class='text-info') }}
                    {{ form.function(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.param_1.label(class='text-info') }}
                    {{ form.param_1(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.param_2.label(class='text-info') }}
                    {{ form.param_2(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.param_3.label(class='text-info') }}
                    {{ form.param_3(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.param_4.label(class='text-info') }}
                    {{ form.param_4(class='form-control') }}
                </div>
                <div class="form-group">
                    <div class="modal-footer">
                        {{ form.submit(class='btn btn-info btn-md') }}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block head %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div id="login">
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" action="" method="post">
                        <h3 class="text-center text-info">Login</h3>
                        <div class="form-group">
<!--                            <label for="username" class="text-info">Username</label><br>-->
                            {{ form.username.label(class='text-info') }}
<!--                            <input type="text" name="username" id="username" class="form-control">-->
                            {{ form.username(class='form-control') }}
                        </div>
                        <div class="form-group">
<!--                            <label for="password" class="text-info">Password</label><br>-->
                            {{ form.password.label(class='text-info') }}
<!--                            <input type="text" name="password" id="password" class="form-control">-->
                            {{ form.password(class='form-control') }}
                        </div>
                        <div class="form-group">
<!--                            <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">-->
                            {{ form.submit(class='btn btn-info btn-md') }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}